apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "best-practices-for-k8s.openshift.io/v1alpha1",
          "kind": "CertsuiteConsolePlugin",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "certsuite-operator",
              "app.kubernetes.io/instance": "certsuiteconsoleplugin-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "certsuiteconsoleplugin",
              "app.kubernetes.io/part-of": "certsuite-operator"
            },
            "name": "certsuiteconsoleplugin-sample",
            "namespace": "certsuite-operator"
          },
          "spec": null
        },
        {
          "apiVersion": "best-practices-for-k8s.openshift.io/v1alpha1",
          "kind": "CertsuiteRun",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "certsuite-operator",
              "app.kubernetes.io/instance": "certsuiterun-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "certsuiterun",
              "app.kubernetes.io/part-of": "certsuite-operator"
            },
            "name": "certsuiterun-sample",
            "namespace": "certsuite-operator"
          },
          "spec": {
            "configMapName": "certsuite-config",
            "enableDataCollection": false,
            "labelsFilter": "observability",
            "logLevel": "info",
            "preflightSecretName": "certsuite-preflight-dockerconfig",
            "showAllResultsLogs": false,
            "showCompliantResourcesAlways": false,
            "timeout": "2h"
          }
        }
      ]
    capabilities: Basic Install
    console.openshift.io/plugins: '["certsuite-plugin"]'
    createdAt: "2025-02-11T10:47:20Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: rh-best-practices-for-k8s-certsuite-operator.v2.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CertsuiteConsolePlugin is the Schema for the certsuiteconsoleplugins
        API
      displayName: Certsuite Console Plugin
      kind: CertsuiteConsolePlugin
      name: certsuiteconsoleplugins.best-practices-for-k8s.openshift.io
      version: v1alpha1
    - description: CertsuiteRun is the Schema for the certsuiteruns API
      displayName: Certsuite Run
      kind: CertsuiteRun
      name: certsuiteruns.best-practices-for-k8s.openshift.io
      version: v1alpha1
  description: Deploys Red Hat's Best Practices for Kubernetes Certification Suite
    Pod to run the Certification Test Suite on target resources.
  displayName: Red Hat's Best Practices for Kubernetes Certification Suite Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: certsuite-cluster-access
      - rules:
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteconsoleplugins
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteconsoleplugins/finalizers
          verbs:
          - update
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteconsoleplugins/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - create
          - delete
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: certsuite-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: certsuite-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: certsuite-operator
          control-plane: controller-manager
        name: certsuite-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                certsuite-operator/sidecar-image: quay.io/rh_ee_shmoran/certsuite-operator:v2.0.0-sidecar
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: SIDECAR_APP_IMG
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['certsuite-operator/sidecar-image']
                - name: CONTROLLER_NS
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/rh_ee_shmoran/certsuite-operator:v2.0.0-controller
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: certsuite-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - configMaps
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteruns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteruns/finalizers
          verbs:
          - update
        - apiGroups:
          - best-practices-for-k8s.openshift.io
          resources:
          - certsuiteruns/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: certsuite-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - cnf
  - certification
  - cloud
  - telco
  links:
  - name: Red Hat's Best Practices for Kubernetes Certification Suite Operator
    url: https://github.com/redhat-best-practices-for-k8s/certsuite-operator
  maturity: alpha
  provider:
    name: Red Hat
  version: 2.0.0
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: certsuite-controller-manager
    failurePolicy: Fail
    generateName: vcertsuiteconsoleplugin.kb.io
    rules:
    - apiGroups:
      - best-practices-for-k8s.openshift.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - certsuiteconsoleplugins
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-best-practices-for-k8s-openshift-io-v1alpha1-certsuiteconsoleplugin
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: certsuite-controller-manager
    failurePolicy: Fail
    generateName: vcertsuiterun.kb.io
    rules:
    - apiGroups:
      - best-practices-for-k8s.openshift.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - certsuiteruns
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-best-practices-for-k8s-openshift-io-v1alpha1-certsuiterun
